// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// spectreasy_nnls_unmix_cpp
arma::mat spectreasy_nnls_unmix_cpp(const arma::mat& Y, const arma::mat& M, const double tol, const int max_outer, const int max_inner);
RcppExport SEXP _spectreasy_spectreasy_nnls_unmix_cpp(SEXP YSEXP, SEXP MSEXP, SEXP tolSEXP, SEXP max_outerSEXP, SEXP max_innerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_outer(max_outerSEXP);
    Rcpp::traits::input_parameter< const int >::type max_inner(max_innerSEXP);
    rcpp_result_gen = Rcpp::wrap(spectreasy_nnls_unmix_cpp(Y, M, tol, max_outer, max_inner));
    return rcpp_result_gen;
END_RCPP
}
// spectreasy_wls_unmix_cpp
arma::mat spectreasy_wls_unmix_cpp(const arma::mat& Y, const arma::mat& M, const arma::vec& noise_floor, const arma::vec& signal_scale, const double max_weight_ratio, const double tol);
RcppExport SEXP _spectreasy_spectreasy_wls_unmix_cpp(SEXP YSEXP, SEXP MSEXP, SEXP noise_floorSEXP, SEXP signal_scaleSEXP, SEXP max_weight_ratioSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type noise_floor(noise_floorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type signal_scale(signal_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type max_weight_ratio(max_weight_ratioSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(spectreasy_wls_unmix_cpp(Y, M, noise_floor, signal_scale, max_weight_ratio, tol));
    return rcpp_result_gen;
END_RCPP
}
// spectreasy_rwls_unmix_cpp
arma::mat spectreasy_rwls_unmix_cpp(const arma::mat& Y, const arma::mat& M, const arma::vec& noise_floor, const arma::vec& signal_scale, const double max_weight_ratio, const double huber_k, const int max_iter, const double robust_tol, const double tol);
RcppExport SEXP _spectreasy_spectreasy_rwls_unmix_cpp(SEXP YSEXP, SEXP MSEXP, SEXP noise_floorSEXP, SEXP signal_scaleSEXP, SEXP max_weight_ratioSEXP, SEXP huber_kSEXP, SEXP max_iterSEXP, SEXP robust_tolSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type noise_floor(noise_floorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type signal_scale(signal_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type max_weight_ratio(max_weight_ratioSEXP);
    Rcpp::traits::input_parameter< const double >::type huber_k(huber_kSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type robust_tol(robust_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(spectreasy_rwls_unmix_cpp(Y, M, noise_floor, signal_scale, max_weight_ratio, huber_k, max_iter, robust_tol, tol));
    return rcpp_result_gen;
END_RCPP
}
// spectreasy_unmix_best_af_cpp
arma::mat spectreasy_unmix_best_af_cpp(const arma::mat& Y, const arma::mat& M, const arma::uvec& fluor_idx, const arma::uvec& af_idx, const std::string& method, const arma::vec& noise_floor, const arma::vec& signal_scale, const double max_weight_ratio, const double tol, const int max_outer, const int max_inner, const int rwls_max_iter);
RcppExport SEXP _spectreasy_spectreasy_unmix_best_af_cpp(SEXP YSEXP, SEXP MSEXP, SEXP fluor_idxSEXP, SEXP af_idxSEXP, SEXP methodSEXP, SEXP noise_floorSEXP, SEXP signal_scaleSEXP, SEXP max_weight_ratioSEXP, SEXP tolSEXP, SEXP max_outerSEXP, SEXP max_innerSEXP, SEXP rwls_max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type fluor_idx(fluor_idxSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type af_idx(af_idxSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type noise_floor(noise_floorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type signal_scale(signal_scaleSEXP);
    Rcpp::traits::input_parameter< const double >::type max_weight_ratio(max_weight_ratioSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_outer(max_outerSEXP);
    Rcpp::traits::input_parameter< const int >::type max_inner(max_innerSEXP);
    Rcpp::traits::input_parameter< const int >::type rwls_max_iter(rwls_max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(spectreasy_unmix_best_af_cpp(Y, M, fluor_idx, af_idx, method, noise_floor, signal_scale, max_weight_ratio, tol, max_outer, max_inner, rwls_max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spectreasy_spectreasy_nnls_unmix_cpp", (DL_FUNC) &_spectreasy_spectreasy_nnls_unmix_cpp, 5},
    {"_spectreasy_spectreasy_wls_unmix_cpp", (DL_FUNC) &_spectreasy_spectreasy_wls_unmix_cpp, 6},
    {"_spectreasy_spectreasy_rwls_unmix_cpp", (DL_FUNC) &_spectreasy_spectreasy_rwls_unmix_cpp, 9},
    {"_spectreasy_spectreasy_unmix_best_af_cpp", (DL_FUNC) &_spectreasy_spectreasy_unmix_best_af_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_spectreasy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
