// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// spectreasy_wls_unmix_cpp
arma::mat spectreasy_wls_unmix_cpp(const arma::mat& Y, const arma::mat& M, const double background_noise, const double tol);
RcppExport SEXP _spectreasy_spectreasy_wls_unmix_cpp(SEXP YSEXP, SEXP MSEXP, SEXP background_noiseSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type background_noise(background_noiseSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(spectreasy_wls_unmix_cpp(Y, M, background_noise, tol));
    return rcpp_result_gen;
END_RCPP
}
// spectreasy_nnls_unmix_cpp
arma::mat spectreasy_nnls_unmix_cpp(const arma::mat& Y, const arma::mat& M, const double tol, const int max_outer, const int max_inner);
RcppExport SEXP _spectreasy_spectreasy_nnls_unmix_cpp(SEXP YSEXP, SEXP MSEXP, SEXP tolSEXP, SEXP max_outerSEXP, SEXP max_innerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_outer(max_outerSEXP);
    Rcpp::traits::input_parameter< const int >::type max_inner(max_innerSEXP);
    rcpp_result_gen = Rcpp::wrap(spectreasy_nnls_unmix_cpp(Y, M, tol, max_outer, max_inner));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spectreasy_spectreasy_wls_unmix_cpp", (DL_FUNC) &_spectreasy_spectreasy_wls_unmix_cpp, 4},
    {"_spectreasy_spectreasy_nnls_unmix_cpp", (DL_FUNC) &_spectreasy_spectreasy_nnls_unmix_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_spectreasy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
