# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spectreasy_wls_unmix_cpp <- function(Y, M, background_noise = 25, tol = 1e-10) {
    .Call(`_spectreasy_spectreasy_wls_unmix_cpp`, Y, M, background_noise, tol)
}

spectreasy_nnls_unmix_cpp <- function(Y, M, tol = 1e-10, max_outer = 500L, max_inner = 500L) {
    .Call(`_spectreasy_spectreasy_nnls_unmix_cpp`, Y, M, tol, max_outer, max_inner)
}

