# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spectreasy_nnls_unmix_cpp <- function(Y, M, tol = 1e-10, max_outer = 500L, max_inner = 500L) {
    .Call(`_spectreasy_spectreasy_nnls_unmix_cpp`, Y, M, tol, max_outer, max_inner)
}

spectreasy_unmix_best_af_cpp <- function(Y, M, fluor_idx, af_idx, method, detector_weights, tol = 1e-10, max_outer = 500L, max_inner = 500L) {
    .Call(`_spectreasy_spectreasy_unmix_best_af_cpp`, Y, M, fluor_idx, af_idx, method, detector_weights, tol, max_outer, max_inner)
}

