# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spectreasy_nnls_unmix_cpp <- function(Y, M, tol = 1e-10, max_outer = 500L, max_inner = 500L, n_threads = 1L) {
    .Call(`_spectreasy_spectreasy_nnls_unmix_cpp`, Y, M, tol, max_outer, max_inner, n_threads)
}

spectreasy_wls_unmix_cpp <- function(Y, M, noise_floor, signal_scale, max_weight_ratio = 1600.0, tol = 1e-10, n_threads = 1L) {
    .Call(`_spectreasy_spectreasy_wls_unmix_cpp`, Y, M, noise_floor, signal_scale, max_weight_ratio, tol, n_threads)
}

spectreasy_rwls_unmix_cpp <- function(Y, M, noise_floor, signal_scale, max_weight_ratio = 1600.0, huber_k = 1.345, max_iter = 1L, robust_tol = 1e-6, tol = 1e-10, n_threads = 1L) {
    .Call(`_spectreasy_spectreasy_rwls_unmix_cpp`, Y, M, noise_floor, signal_scale, max_weight_ratio, huber_k, max_iter, robust_tol, tol, n_threads)
}

spectreasy_autospectral_assign_cpp <- function(Y, unmixed_markers, v_library, r_library, denominator, valid_indices, n_threads = 1L) {
    .Call(`_spectreasy_spectreasy_autospectral_assign_cpp`, Y, unmixed_markers, v_library, r_library, denominator, valid_indices, n_threads)
}

spectreasy_unmix_best_af_cpp <- function(Y, M, fluor_idx, af_idx, method, noise_floor, signal_scale, max_weight_ratio = 1600.0, tol = 1e-10, max_outer = 500L, max_inner = 500L, rwls_max_iter = 1L, n_threads = 1L) {
    .Call(`_spectreasy_spectreasy_unmix_best_af_cpp`, Y, M, fluor_idx, af_idx, method, noise_floor, signal_scale, max_weight_ratio, tol, max_outer, max_inner, rwls_max_iter, n_threads)
}

